# oa-system/src/main/resources/application-dev.yml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa_jianxin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: ${DB_PASSWORD:newtouch@2026}

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
